### ISSUE TITLE
Support of two TRCT5000 devices per meter to detect direction of meter disc

### ISSUE THREAD

**Issue by huckes** [Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000#22]
With installed solar panels it might happen that the Ferraris Meter runs in reverse order as energy is fed into the electric net if the panels provide more energy as consumed locally. So far the project does not detect the direction change and the energy supplied is counted as consumtion.

With two TCRT5000 modules the rotating direction of the meter disk can be detected by evaluating the detection sequence of the disc mark. This should result in either a message reporting the direction or a negative value of the power calculated or both.

As this project supports several meters with a TCRT-module per each, one approach could be to combine the detection of two TCRT-modules mounted to the screen of one meter.

I already developed a design how to mount two TCRT5000 modules to the meter screen. You can find it in https://www.thingiverse.com/thing:5820811

**Comment by EtlamGit** [comment]
Yes, very important note with reverse rotation.
You printed 3D design prevents reading the meter manually. So it might me better to change orientation for both to the bottom. I even read that some people use the sensors in 90°. Have you tested something like that?

From the photos I assume, that you are using the sensors like they where delivered?
I ask, because I have severe problems with oscillation during low consumption.
My plan is to modify the sensors to get some hysteresis.

A problem I see with supporting two rotation directions is: how to design the configuration dialog?
Because now, each meter is configured separately. When two are combined, we either loose half of the supported number or need some complicated UI. Any ideas how to do that?

**Comment by huckes** [comment]
Thanks for your comment and the hint that the plate covers the meter. I posted an additional design on Thingiverse, where the meter can be read. In my case there are two totalizers (day/night-time). The lower totalizer can be read from the side.

Yes, I used the modules as delivered. A hysteresis could make it easier for this project. 

I found a schematic of the sensor here: https://www.hotmcu.com/ir-reflective-sensor-tcrt5000-p-184.html
In the schematic the analogue output is missing, but it seems to lead directly to the '-'-input of the OP. With a resistor between OP-output and '+'-input a hysteresis could be implemented, as far as I can remember my electronic lessones ages ago.  
But for a general purpose module the possibillity to adjust the hysteries were needed too. And two potentiometers would interfere each other in this easy case.

I had also some problems to find a mounting position to reduce false detection. Therefore I tried to find the best position for the optocouplers. In my case it resulted in mounting the optocouplers in horizontal orientation to the disc to minimize reflections from the 'silver'-cover plate. And the reason for one module top of and the other one below the disc is to bring both opto-transistors as near as possible to the middle and the IR-leds right and left from these. With this mounting I had the best results of clear detection vs. false detection. Therefor I skipped the options to mount the modules side by side or 90° turned by.

I could not discover oscillation. But there might occur false detection due to unround disc or reflections of the disc teeth, if it is this, what you mean. 
A false detection lasts usually only a short time in relation to the detection of the disc mark. These false detections could be elimited by defining a minimum length of detection duration. And addtionally a transit of the disc causes also a concurrent detection period of both modules over a minimum duration.

In case of really oscillating output I would try to bridge a small capacitator betwenn VCC and ground directly at the TCRT-modules.

I must confess I did'nt looked up the code in detail so far, so false detection might be filtered already. I'm still struggeling a bit with getting the cloned projet running on my PIO installation. The installation of the iot-framework causes error messages which I could not solve so far due to the fact that I'm a fairly new PIO-user.

**Comment by huckes** [comment]
Hi again, concerning support of two rotation direction i forgot to comment:

On a first step it probably could be possible to combine only explicitly two input channels (e.g. the first and the last) as an option to be selected by e.g. compiler switch. Then only one channel gets lost and the effort to be done changing the UI could be postponed if this option is wanted by other users too. Calibration of the second sensor involved can be done by changing the wires without changing the UI. The introduction of a '-'-character or another mark for revers rotation is not a severe problem for the UI, i hope.

**Comment by EtlamGit** [comment]
So many (good) topics you address . . . I will try to answer them during the next weeks.

Just to give some background: I just started using this project some weeks ago. The original author does not have a Ferraris meter anymore, so it would be task of others to continue. I still struggle with stability issues (WLAN, oscillation) but since yesterday I think I have solved them.

I like the idea to be able to count in both directions.

Regarding the oscillations:
Others call them bouncing, but this is not mechanical bouncing as this would have a defined time duration and could be solved with typical de-bouncing techniques.
Just imagine the meter is turning very very slow. Then the change between silver to red is not a hard cut, but a very slow slope. At the input of the comparator you will get any intermediate voltage for any time duration (it has just to be slow enough).
As the comparator is wired in simple comparator mode, a threshold is set via the potentiometer. At the moment the incoming analog value from the IR detector is reaching the threshold, the comparator will change output state. This will change the green LED, which will change the current consumption of the sensor. This will cause a supply voltage drop/rise that may change the operation point of the comparator. So it will switch again, what will change the supply voltage which will change . . .
As conclusion: if the meter is slow enough, it is possible that the output will toggle at any arbitrary frequency for any arbitrary time. It is impossible to de-bounce that. The only solution is an analog hysteresis for the comparator.
And you remember right, it is just a resistor (100k ..1M) from + to out. With that simple solution it is not possible to get a defined hysteresis, but at least something in that direction. For a real and well designed hysteresis you would have to place another resistor in front of the + input. But the layout of the sensor prevents easy access to that wire.

**Comment by huckes** [comment]
Thanks a bunch for your reply and that you will continue working on that project.

My Ferraris energy counter will be replaced by a modern type latest in 2027.

I also detected bouncing you described during the beginninng and the end of the red-zone-passing. Of course more visible during slow speed, but I could see this also on higher speed, if the sensors were mounted unhandy. As soon as the red-zone covered most of the sensor, this bouncing stoped. 

Excuse me please if I write too much stuff already known or considered:

One fact which might be less considered: The sensor is a reflective sensor mainly to detect a certain distance.However, in this project it is used to detect a colour change. During the 'silver'-phase it shall detect 'near' (LED on), during the 'red'-phase it shall detect far (LED off). So the principle used is, that the red zone (hopefully) reflects less IR-light than the silver zone.
To do this with a fairly good reliabillity the sensor should 'see' the disc and as less as possible the plate covering the innards of the energy-counter. 

Thats the reason why I put a mask over the sensor LED, to reduce the IR-light projected to the plate (not completely, but noticeable).
With my way of mounting I could measure on the analogue pin a voltage-ratio of about 1:1,5 in best case (1,2V silver, 1,8V red).
The better this ratio the fewer the bounces.

I just measured the current used by the sensor: 15,4 mA with LED off and 17.2 mA with LED on. So the LED uses less than 2 mA. If this 2 mA leads to the effect you described due to power drop, I assume either a weak power source or too long or too thin cables. Nethertheless for testing purpose I would bridge the power pins of the sensor with a capacitor of some µF and perhaps a high frequency blocking capacitor with some nF. If this does not help removing the LED or it's series resistor should work.

I dropped two videos to youtube with slow and fast disc speed (+ 2,1 KW) with my test installation. 

Low speed:  https://youtu.be/MF94PpN3KXA 
Fast speed: https://youtu.be/FgT2etckv6I 

I'm still struggeling get the code running on my PIO installation. Following the intallation guide of the esp8266-iot-framework still ends up with error messages. Other esp8266-based code I tried could be compliled and uploaded successfully. I'll keep trying ....

**Comment by EtlamGit** [comment]
Very interesting.
I get a voltage difference of only 25mV ! Even with optimal mounting position.
It is possible to control the mounting with a digital camera. You can see the IR light and if it gets reflected or not with an old smartphone (my new one has an IR filter). And I can clearly see the reflected light from silver and darkness for the red mark.
I also tried your lightshade, no effect at all.
(New sensors are ordered)

**Comment by huckes** [comment]
25mV seems to be insufficient. 

Reasons beside mounting could be: 
- weak TCRT-Modules, 
- geometric problems e.g. the slot is too narrow so too much light is reflected by the plate or the distance between disc and pane ist to far,
- optical reason: the red zone reflects IR-light nearly as good as the silver zone.

You must ensure, that the TCRT modules are mounted directly to the pane.
In annother article a user put pieces of shrink tube over the IR-led and the opto-trans. 

A proffessional solution were to put a lense in front of the IR-led.

**Comment by EtlamGit** [comment]
Hallo Hans, sorry dass ich so lange beschäftigt war! Aber ich musste zuerst meinen Zähler überhaupt zum Zählen bringen und danach dafür sorgen, dass er zum Testen auch mal rückwärt läuft.

Finally I solved my voltage difference issue and can count now. It needed several TCRT5000 modules and in the end I had to design and manufacture my own board. Probably my glass cover is disturbing the IR light.

My new board is out of the box capable of dual direction counting!
I will start testing to count in dual directions from now on.

**Comment by EtlamGit** [comment]
It is not possible to upload binaries here, so I changed file ending from bin to png . . .

![nodemcuv2](https://github.com/Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000/assets/5821779/32ea6682-c5c0-48cb-99fe-d5d62e5088ef)
![d1_mini](https://github.com/Eisbaeeer/Ferraris_MQTT_Energy_Counter_Meter_TCRT5000/assets/5821779/b9241a55-6651-4f3c-abe8-a7b4cea8c686)

**Comment by huckes** [comment]
Hi, thanks for your note. 
In the meantime I switched to the Shelly Pro 3EM, so I do not need the detection of the ferraris-wheel anymore.
Greetings, Hans

**Comment by EtlamGit** [comment]
I assume the Shelly will work more stable. But they are quite expensive.

First tests here look promising with nice counting in both directions.
Thank you for the idea of this feature!

**Comment by Eisbaeeer** [comment]
solved with PR #23
